
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: thusithanc/gke-apptest-backend:latest
    volumes:
      - ./backend/backend:/app/backend
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: ./streamlit-ui
      dockerfile: Dockerfile
    container_name: streamlit-ui
    image: thusithanc/gke-apptest-ui:latest
    ports:
      - "3001:3001"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000