apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-backend-image:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tnc
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: tnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: your-ui-image:latest
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: http://backend:8000
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: tnc
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: gke-l7-gateway
spec:
  controllerName: networking.gke.io/gateway
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: tnc-gateway
  namespace: tnc
spec:
  gatewayClassName: gke-l7-gateway
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          app: ui
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: ui-route
  namespace: tnc
spec:
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    forwardTo:
    - serviceName: ui
      port: 8501