apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: backend-gateway
  namespace: tnc
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      certificateRefs:
        - kind: Secret
          name: tls-cert
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: backend-gateway-policy
  namespace: tnc
spec:
  default:
    allowGlobalAccess: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: backend-gateway

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: tnc
spec:
  parentRefs:
  - name: backend-gateway
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /api/
    backendRefs:
      - name: backend-service
        port: 80
  - matches:
      - path:
          value: /
    backendRefs:
      - name: streamlit-ui-service
        port: 80
---

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: backend-health-check
  namespace: tnc
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: TCP
      httpHealthCheck:
        requestPath: /health
        port: 80
  targetRef:
    group: ""
    kind: Service
    name: backend-service

---

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ui-health-check
  namespace: tnc
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: TCP
      httpHealthCheck:
        requestPath: /
        port: 80
  targetRef:
    group: ""
    kind: Service
    name: streamlit-ui-service

# Setting up IAP
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ui-policy-default
  namespace: tnc
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-oauth-secret
      clientID: $IAP_CLIENT_ID
  targetRef:
    group: ""
    kind: Service
    name: streamlit-ui-service

---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: backend-policy-default
  namespace: tnc
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-oauth-secret
      clientID: $IAP_CLIENT_ID
  targetRef:
    group: ""
    kind: Service
    name: backend-service